import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    // Main barrel
    index: "src/index.ts",
    // Individual component entries (tree-shakeable)
    "components/ui/button": "src/components/ui/button.tsx",
    "components/ui/input": "src/components/ui/input.tsx",
    "components/ui/select": "src/components/ui/select.tsx",
    "components/ui/combobox": "src/components/ui/combobox.tsx",
    "components/ui/checkbox": "src/components/ui/checkbox.tsx",
    "components/ui/radio-group": "src/components/ui/radio-group.tsx",
    "components/ui/switch": "src/components/ui/switch.tsx",
    "components/ui/dialog": "src/components/ui/dialog.tsx",
    "components/ui/alert-dialog": "src/components/ui/alert-dialog.tsx",
    "components/ui/dropdown-menu": "src/components/ui/dropdown-menu.tsx",
    "components/ui/tabs": "src/components/ui/tabs.tsx",
    "components/ui/table": "src/components/ui/table.tsx",
    "components/ui/card": "src/components/ui/card.tsx",
    "components/ui/alert": "src/components/ui/alert.tsx",
    "components/ui/sonner": "src/components/ui/sonner.tsx",
    "components/ui/popover": "src/components/ui/popover.tsx",
    "components/ui/tooltip": "src/components/ui/tooltip.tsx",
    "components/ui/drawer": "src/components/ui/drawer.tsx",
    "components/ui/navbar": "src/components/ui/navbar.tsx",
    "components/ui/accordion": "src/components/ui/accordion.tsx",
    "components/ui/avatar": "src/components/ui/avatar.tsx",
    "components/ui/badge": "src/components/ui/badge.tsx",
    "components/ui/breadcrumb": "src/components/ui/breadcrumb.tsx",
    "components/ui/label": "src/components/ui/label.tsx",
    "components/ui/textarea": "src/components/ui/textarea.tsx",
    "components/ui/slider": "src/components/ui/slider.tsx",
    "components/ui/toggle": "src/components/ui/toggle.tsx",
    "components/ui/segment-control": "src/components/ui/segment-control.tsx",
    "components/ui/split-button": "src/components/ui/split-button.tsx",
    "components/ui/separator": "src/components/ui/separator.tsx",
    "components/ui/skeleton": "src/components/ui/skeleton.tsx",
    "components/ui/spinner": "src/components/ui/spinner.tsx",
    "components/ui/progress": "src/components/ui/progress.tsx",
    "components/ui/pagination": "src/components/ui/pagination.tsx",
    "components/ui/tag": "src/components/ui/tag.tsx",
    "components/ui/status": "src/components/ui/status.tsx",
    "components/ui/empty": "src/components/ui/empty.tsx",
    "components/ui/hover-card": "src/components/ui/hover-card.tsx",
    "components/ui/radio-tile": "src/components/ui/radio-tile.tsx",
    "components/ui/input-group": "src/components/ui/input-group.tsx",
    "components/ui/key-value-pair": "src/components/ui/key-value-pair.tsx",
    "components/ui/editor-tabs": "src/components/ui/editor-tabs.tsx",
    // Lib utilities
    "lib/utils": "src/lib/utils.ts",
    "lib/button-variants": "src/lib/button-variants.ts",
  },
  format: ["esm"],
  // DTS disabled until pre-existing type errors are fixed
  dts: false,
  sourcemap: true,
  splitting: true,
  treeshake: true,
  external: ["react", "react-dom", "next-themes"],
  outDir: "dist",
  clean: true,
  jsx: "automatic",
  banner: { js: '"use client";' },
})
