// Generated by scripts/generate-icon-data.mjs — do not edit by hand.
// Source: React output of each component in packages/dbui/src/components/icons/

// Imported on demand by the icon browser — one chunk per category, so opening
// the page pays for the category it shows and not for the other three.

/** viewBox is present only when it is not the 0 0 16 16 the set draws on. */
export type Glyph = { viewBox?: string; body: string }

const glyphs: Record<string, Glyph> = {
  "ArrowsUpDown": {"body":"<path fill=\"currentColor\" d=\"M5.03 1 1 5.03l1.06 1.061 2.22-2.22v6.19h1.5V3.87L8 6.091l1.06-1.06zM11.03 15.121l4.03-4.03-1.06-1.06-2.22 2.219V6.06h-1.5v6.19l-2.22-2.22L7 11.091z\"></path>"},
  "Calendar": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M4.5 0v2H1.75a.75.75 0 0 0-.75.75v11.5c0 .414.336.75.75.75h12.5a.75.75 0 0 0 .75-.75V2.75a.75.75 0 0 0-.75-.75H11.5V0H10v2H6V0zm9 3.5v2h-11v-2zM2.5 7v6.5h11V7z\" clip-rule=\"evenodd\"></path>"},
  "Check": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"m15.06 3.56-9.53 9.531L1 8.561 2.06 7.5l3.47 3.47L14 2.5z\" clip-rule=\"evenodd\"></path>"},
  "CheckCircle": {"body":"<path fill=\"currentColor\" d=\"M11.53 6.53 7 11.06 4.47 8.53l1.06-1.06L7 8.94l3.47-3.47z\"></path><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13\" clip-rule=\"evenodd\"></path>"},
  "ChevronDown": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8 8.917 10.947 6 12 7.042 8 11 4 7.042 5.053 6z\" clip-rule=\"evenodd\"></path>"},
  "ChevronLeft": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M7.083 8 10 10.947 8.958 12 5 8l3.958-4L10 5.053z\" clip-rule=\"evenodd\"></path>"},
  "ChevronRight": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8.917 8 6 5.053 7.042 4 11 8l-3.958 4L6 10.947z\" clip-rule=\"evenodd\"></path>"},
  "ChevronUp": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8 7.083 5.053 10 4 8.958 8 5l4 3.958L10.947 10z\" clip-rule=\"evenodd\"></path>"},
  "CircleOutlineLarge": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8 1.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8\" clip-rule=\"evenodd\"></path>"},
  "Close": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M6.97 8.03 2 3.06 3.06 2l4.97 4.97L13 2l1.06 1.06-4.969 4.97 4.97 4.97L13 14.06 8.03 9.092l-4.97 4.97L2 13z\" clip-rule=\"evenodd\"></path>"},
  "Dash": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M15 8.75H1v-1.5h14z\" clip-rule=\"evenodd\"></path>"},
  "File": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M2 1.75A.75.75 0 0 1 2.75 1h6a.75.75 0 0 1 .53.22l4.5 4.5c.141.14.22.331.22.53v9a.75.75 0 0 1-.75.75H2.75a.75.75 0 0 1-.75-.75zm1.5.75v12h9V7H8.75A.75.75 0 0 1 8 6.25V2.5zm6 1.06 1.94 1.94H9.5z\" clip-rule=\"evenodd\"></path>"},
  "Folder": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M0 2.75A.75.75 0 0 1 .75 2h3.922c.729 0 1.428.29 1.944.805L7.811 4h7.439a.75.75 0 0 1 .75.75v8.5a.75.75 0 0 1-.75.75H.75a.75.75 0 0 1-.75-.75zm1.5.75v9h13v-7h-7a.75.75 0 0 1-.53-.22L5.555 3.866a1.25 1.25 0 0 0-.883-.366z\" clip-rule=\"evenodd\"></path>"},
  "InfoSmall": {"body":"<path fill=\"currentColor\" d=\"M7.25 10.5v-3h1.5v3zM8 5a.75.75 0 1 1 0 1.5A.75.75 0 0 1 8 5\"></path><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12m0-1.5a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9\" clip-rule=\"evenodd\"></path>"},
  "Loading": {"viewBox":"0 0 24 24","body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M23.212 12a.79.79 0 0 1-.789-.788 9.6 9.6 0 0 0-.757-3.751 9.66 9.66 0 0 0-5.129-5.129 9.6 9.6 0 0 0-3.749-.755.788.788 0 0 1 0-1.577c1.513 0 2.983.296 4.365.882a11.1 11.1 0 0 1 3.562 2.403 11.157 11.157 0 0 1 3.283 7.927.785.785 0 0 1-.786.788\" clip-rule=\"evenodd\"></path>"},
  "Overflow": {"body":"<path fill=\"currentColor\" d=\"M8 1a1.75 1.75 0 1 0 0 3.5A1.75 1.75 0 0 0 8 1M8 6.25a1.75 1.75 0 1 0 0 3.5 1.75 1.75 0 0 0 0-3.5M8 11.5A1.75 1.75 0 1 0 8 15a1.75 1.75 0 0 0 0-3.5\"></path>"},
  "Plus": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M7.25 7.25V1h1.5v6.25H15v1.5H8.75V15h-1.5V8.75H1v-1.5z\" clip-rule=\"evenodd\"></path>"},
  "Search": {"body":"<g><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8 1a7 7 0 1 0 4.39 12.453l2.55 2.55 1.06-1.06-2.55-2.55A7 7 0 0 0 8 1M2.5 8a5.5 5.5 0 1 1 11 0 5.5 5.5 0 0 1-11 0\" clip-rule=\"evenodd\"></path></g>"},
  "SidebarOpen": {"body":"<path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M13 1a3 3 0 0 1 3 3v8l-.004.154A3 3 0 0 1 13 15H3l-.154-.004a3 3 0 0 1-2.842-2.842L0 12V4a3 3 0 0 1 3-3zM3 2.5A1.5 1.5 0 0 0 1.5 4v8A1.5 1.5 0 0 0 3 13.5h1.5v-11zm3 11h7a1.5 1.5 0 0 0 1.5-1.5V4A1.5 1.5 0 0 0 13 2.5H6z\" clip-rule=\"evenodd\"></path>"},
  "Slash": {"body":"<path d=\"M11.5 2L9 13H7.5L10 2H11.5Z\" fill=\"currentColor\"></path><circle cx=\"8\" cy=\"12\" r=\"1\" fill=\"currentColor\"></circle><circle cx=\"5\" cy=\"12\" r=\"1\" fill=\"currentColor\"></circle>"},
  "Warning": {"body":"<path fill=\"currentColor\" d=\"M7.25 10V6.5h1.5V10zM8 12.5A.75.75 0 1 0 8 11a.75.75 0 0 0 0 1.5\"></path><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M8 1a.75.75 0 0 1 .649.374l7.25 12.5A.75.75 0 0 1 15.25 15H.75a.75.75 0 0 1-.649-1.126l7.25-12.5A.75.75 0 0 1 8 1m0 2.245L2.052 13.5h11.896z\" clip-rule=\"evenodd\"></path>"},
  "XCircle": {"body":"<path fill=\"currentColor\" d=\"M6.94 8 4.97 6.03l1.06-1.06L8 6.94l1.97-1.97 1.06 1.06L9.06 8l1.97 1.97-1.06 1.06L8 9.06l-1.97 1.97-1.06-1.06z\"></path><path fill=\"currentColor\" fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13\" clip-rule=\"evenodd\"></path>"},
}

export default glyphs
