// Generated by scripts/generate-gallery.mjs — do not edit by hand.
// Source of truth: packages/dbui-cli/src/api.mjs (listComponents).

export type GalleryItem = {
  name: string
  slug: string
  useFor: string
  storyId: string | null
}

export type GalleryGroup = {
  key: string
  label: string
  blurb: string
  items: GalleryItem[]
}

export const galleryGroups: GalleryGroup[] = [
  {
    "key": "action",
    "label": "Action",
    "blurb": "Does something the moment it is clicked",
    "items": [
      {
        "name": "Button",
        "slug": "button",
        "useFor": "Any click action — primary CTAs, toolbar actions, icon buttons, menu triggers",
        "storyId": "components-actions-button--playground"
      },
      {
        "name": "Split Button",
        "slug": "split-button",
        "useFor": "A primary action with related alternatives in a dropdown (3–5 alternatives)",
        "storyId": "components-actions-splitbutton--playground"
      },
      {
        "name": "Toggle Button",
        "slug": "toggle",
        "useFor": "Buttons that need to remember pressed state (icon toolbar toggles, filter pills)",
        "storyId": "components-actions-toggle--playground"
      }
    ]
  },
  {
    "key": "input",
    "label": "Input",
    "blurb": "Collects a value the screen reads later",
    "items": [
      {
        "name": "Checkbox",
        "slug": "checkbox",
        "useFor": "Multi-select within a group, indeterminate parent states, form fields with submit",
        "storyId": "components-controls-checkbox--playground"
      },
      {
        "name": "Combobox",
        "slug": "combobox",
        "useFor": "Pick one or many from 10+ options with search",
        "storyId": "components-controls-combobox--playground"
      },
      {
        "name": "Date Range",
        "slug": "date-range",
        "useFor": "Pair of start + end date fields (run history, audit windows, time-window filters)",
        "storyId": null
      },
      {
        "name": "Input",
        "slug": "input",
        "useFor": "Single-line text fields, numbers, search, email — md size by default",
        "storyId": "components-controls-input--playground"
      },
      {
        "name": "Select",
        "slug": "select",
        "useFor": "Pick one from ≤10 fixed options",
        "storyId": "components-controls-select--playground"
      },
      {
        "name": "Slider",
        "slug": "slider",
        "useFor": "Continuous range selection where the rough value matters more than the exact one",
        "storyId": "components-controls-slider--playground"
      },
      {
        "name": "Switch",
        "slug": "switch",
        "useFor": "Immediate on/off toggles that take effect without a save action",
        "storyId": "components-controls-switch--playground"
      },
      {
        "name": "Textarea",
        "slug": "textarea",
        "useFor": "Multi-line text input that auto-grows (field-sizing: content)",
        "storyId": "components-controls-textarea--playground"
      }
    ]
  },
  {
    "key": "selection",
    "label": "Selection",
    "blurb": "Picks one of a few choices that are already on screen",
    "items": [
      {
        "name": "Radio",
        "slug": "radio-group",
        "useFor": "One-of-many choice for 2–7 options with text labels",
        "storyId": "components-controls-radiogroup--playground"
      },
      {
        "name": "Radio Tile",
        "slug": "radio-tile",
        "useFor": "Visual one-of-many with icon + title + description (2–5 options)",
        "storyId": "components-controls-radiotile--playground"
      },
      {
        "name": "Segment Control",
        "slug": "segment-control",
        "useFor": "Single-value selection in toolbars (2–5 single-word items)",
        "storyId": "components-actions-segmentcontrol--playground"
      }
    ]
  },
  {
    "key": "menu",
    "label": "Menu",
    "blurb": "Holds actions in a list that opens from a trigger",
    "items": [
      {
        "name": "Dropdown Menu",
        "slug": "dropdown-menu",
        "useFor": "Click-triggered action menus, kebab/overflow menus, item-level menus",
        "storyId": "components-controls-dropdownmenu--playground"
      }
    ]
  },
  {
    "key": "overlay",
    "label": "Overlay",
    "blurb": "Puts content above the page and takes focus with it",
    "items": [
      {
        "name": "Alert Dialog",
        "slug": "alert-dialog",
        "useFor": "Confirming destructive or irreversible actions",
        "storyId": "components-overlays-alertdialog--playground"
      },
      {
        "name": "Dialog",
        "slug": "dialog",
        "useFor": "Focused tasks and forms in an overlay (max one open at a time)",
        "storyId": "components-overlays-dialog--playground"
      },
      {
        "name": "Drawer",
        "slug": "drawer",
        "useFor": "Detail panels, settings, secondary content sliding in from the right",
        "storyId": "components-overlays-drawer--playground"
      },
      {
        "name": "Hover Card",
        "slug": "hover-card",
        "useFor": "Rich preview content on hover (user profiles, link previews)",
        "storyId": "components-overlays-hovercard--playground"
      },
      {
        "name": "Popover",
        "slug": "popover",
        "useFor": "Date pickers, color pickers, mini-forms, rich tooltips with content",
        "storyId": "components-overlays-popover--playground"
      },
      {
        "name": "Toast",
        "slug": "sonner",
        "useFor": "Transient feedback toasts after an action (save, copy, delete)",
        "storyId": "components-overlays-toast--playground"
      },
      {
        "name": "Tooltip",
        "slug": "tooltip",
        "useFor": "One-line hover hints, especially on icon-only buttons (size=\"icon-md\")",
        "storyId": "components-overlays-tooltip--playground"
      }
    ]
  },
  {
    "key": "navigation",
    "label": "Navigation",
    "blurb": "Moves the reader between views",
    "items": [
      {
        "name": "Breadcrumb",
        "slug": "breadcrumb",
        "useFor": "Hierarchical path back to root (last item is current page)",
        "storyId": "components-content-breadcrumb--playground"
      },
      {
        "name": "Editor Tabs",
        "slug": "editor-tabs",
        "useFor": "Code-editor style closeable tabs with file-type icons",
        "storyId": "components-content-editortabs--playground"
      },
      {
        "name": "Navbar",
        "slug": "navbar",
        "useFor": "Top-level product navigation (workspace switcher, global actions)",
        "storyId": "components-content-navbar--default"
      },
      {
        "name": "Pagination",
        "slug": "pagination",
        "useFor": "Paged tables with previous/next, ellipsis for large counts",
        "storyId": "components-content-pagination--playground"
      },
      {
        "name": "Tabs",
        "slug": "tabs",
        "useFor": "Switch between sibling content panels of equal importance (2–7 tabs)",
        "storyId": "components-content-tabs--playground"
      }
    ]
  },
  {
    "key": "feedback",
    "label": "Feedback",
    "blurb": "Reports what the system is doing or what just happened",
    "items": [
      {
        "name": "Alert",
        "slug": "alert",
        "useFor": "Persistent inline messages tied to page content (info / warning / danger / success)",
        "storyId": "components-overlays-alert--playground"
      },
      {
        "name": "Badge",
        "slug": "badge",
        "useFor": "Short status labels and counts (1–2 words)",
        "storyId": "components-content-badge--playground"
      },
      {
        "name": "Empty",
        "slug": "empty",
        "useFor": "Zero-data states with title, description, primary action",
        "storyId": "components-content-empty--playground"
      },
      {
        "name": "Progress Bar",
        "slug": "progress",
        "useFor": "Determinate progress with a known endpoint (percentage or step count)",
        "storyId": "components-content-progress--playground"
      },
      {
        "name": "Skeleton",
        "slug": "skeleton",
        "useFor": "Initial-load placeholders that match the shape of the incoming content",
        "storyId": "components-content-skeleton--playground"
      },
      {
        "name": "Spinner",
        "slug": "spinner",
        "useFor": "Indeterminate loading >1 s",
        "storyId": "components-content-spinner--playground"
      },
      {
        "name": "Status",
        "slug": "status",
        "useFor": "Status with icon + label (running, error, success, online, …)",
        "storyId": "components-content-status--playground"
      }
    ]
  },
  {
    "key": "display",
    "label": "Display",
    "blurb": "Shows data the screen already has",
    "items": [
      {
        "name": "Avatar",
        "slug": "avatar",
        "useFor": "User identity (image, fallback initials, default icon)",
        "storyId": "components-content-avatar--playground"
      },
      {
        "name": "Card",
        "slug": "card",
        "useFor": "Bounded content surfaces with elevation (rounded-4, shadow)",
        "storyId": "components-content-card--playground"
      },
      {
        "name": "Key Value Pair",
        "slug": "key-value-pair",
        "useFor": "Metadata in detail sidebars (key uses muted-foreground; value uses foreground)",
        "storyId": "components-content-keyvaluepair--playground"
      },
      {
        "name": "Table",
        "slug": "table",
        "useFor": "Structured data with sortable columns, row hover, optional row actions",
        "storyId": "components-content-table--playground"
      },
      {
        "name": "Tag",
        "slug": "tag",
        "useFor": "Removable filter chips, key:value labels in faceted filters",
        "storyId": "components-content-tag--playground"
      },
      {
        "name": "Tree",
        "slug": "data-tree",
        "useFor": "Hierarchical data browsing (catalogs, schemas, tables) — every node has a typed icon",
        "storyId": "components-content-tree-data-tree--default"
      }
    ]
  },
  {
    "key": "layout",
    "label": "Layout",
    "blurb": "Arranges other components and carries no content of its own",
    "items": [
      {
        "name": "Accordion",
        "slug": "accordion",
        "useFor": "Settings panels, filter groups, FAQ-style content",
        "storyId": "components-content-accordion--playground"
      },
      {
        "name": "Aspect Ratio",
        "slug": "aspect-ratio",
        "useFor": "Lock image/video proportions inside cards and grids",
        "storyId": null
      },
      {
        "name": "Input Group",
        "slug": "input-group",
        "useFor": "Attach icons, buttons, or text addons to an Input (e.g. search + clear, prefix/suffix)",
        "storyId": "components-controls-inputgroup--playground"
      },
      {
        "name": "Label",
        "slug": "label",
        "useFor": "The name of a form field",
        "storyId": null
      },
      {
        "name": "Separator",
        "slug": "separator",
        "useFor": "Visual divider between content groups",
        "storyId": "components-content-separator--playground"
      }
    ]
  },
  {
    "key": "chrome",
    "label": "Chrome",
    "blurb": "Frames the page, so a screen takes it from a shell rather than building one",
    "items": [
      {
        "name": "Controls Bar",
        "slug": "controls-bar",
        "useFor": "Filter / search / sort row below PageHeader (Shell A list pages, etc.)",
        "storyId": "components-compositions-controls-bar--filtersonly"
      },
      {
        "name": "Page Header",
        "slug": "page-header",
        "useFor": "Top of every content surface — title row + optional Tabs row",
        "storyId": "components-compositions-page-header--titleonly"
      },
      {
        "name": "Platform Header",
        "slug": "platform-header",
        "useFor": "The Databricks top bar (sidebar toggle, search, workspace, Genie, apps, profile)",
        "storyId": "components-compositions-platform-header--default"
      }
    ]
  }
]

export const galleryTotal = 48
