// Generated by scripts/generate-gallery.mjs — do not edit by hand.
// Source of truth: packages/dbui-cli/src/api.mjs (listComponents).

export type GalleryItem = {
  name: string
  slug: string
  useFor: string
  storyId: string | null
}

export type GalleryGroup = {
  key: string
  label: string
  blurb: string
  items: GalleryItem[]
}

export const galleryGroups: GalleryGroup[] = [
  {
    "key": "action",
    "label": "Action",
    "blurb": "Does something the moment it is clicked",
    "items": [
      {
        "name": "Button",
        "slug": "button",
        "useFor": "Any click action — primary CTAs, toolbar actions, icon buttons, menu triggers",
        "storyId": "components-actions-button--playground"
      },
      {
        "name": "Segment Control",
        "slug": "segment-control",
        "useFor": "Single-value selection in toolbars (2–5 single-word items)",
        "storyId": "components-actions-segmentcontrol--playground"
      },
      {
        "name": "Split Button",
        "slug": "split-button",
        "useFor": "A primary action with related alternatives in a dropdown (3–5 alternatives)",
        "storyId": "components-actions-splitbutton--playground"
      },
      {
        "name": "Toggle Button",
        "slug": "toggle",
        "useFor": "Buttons that need to remember pressed state (icon toolbar toggles, filter pills)",
        "storyId": "components-actions-toggle--playground"
      }
    ]
  },
  {
    "key": "controls",
    "label": "Controls",
    "blurb": "Collects or changes a value the screen reads later",
    "items": [
      {
        "name": "Checkbox",
        "slug": "checkbox",
        "useFor": "Multi-select within a group, indeterminate parent states, form fields with submit",
        "storyId": "components-controls-checkbox--playground"
      },
      {
        "name": "Combobox",
        "slug": "combobox",
        "useFor": "Pick one or many from 10+ options with search",
        "storyId": "components-controls-combobox--playground"
      },
      {
        "name": "Dropdown Menu",
        "slug": "dropdown-menu",
        "useFor": "Click-triggered action menus, kebab/overflow menus, item-level menus",
        "storyId": "components-controls-dropdownmenu--playground"
      },
      {
        "name": "Input",
        "slug": "input",
        "useFor": "Single-line text fields, numbers, search, email — md size by default",
        "storyId": "components-controls-input--playground"
      },
      {
        "name": "Input Group",
        "slug": "input-group",
        "useFor": "Attach icons, buttons, or text addons to an Input (e.g. search + clear, prefix/suffix)",
        "storyId": "components-controls-inputgroup--playground"
      },
      {
        "name": "Radio",
        "slug": "radio-group",
        "useFor": "One-of-many choice for 2–7 options with text labels",
        "storyId": "components-controls-radiogroup--playground"
      },
      {
        "name": "Radio Tile",
        "slug": "radio-tile",
        "useFor": "Visual one-of-many with icon + title + description (2–5 options)",
        "storyId": "components-controls-radiotile--playground"
      },
      {
        "name": "Select",
        "slug": "select",
        "useFor": "Pick one from ≤10 fixed options",
        "storyId": "components-controls-select--playground"
      },
      {
        "name": "Slider",
        "slug": "slider",
        "useFor": "Continuous range selection where the rough value matters more than the exact one",
        "storyId": "components-controls-slider--playground"
      },
      {
        "name": "Switch",
        "slug": "switch",
        "useFor": "Immediate on/off toggles that take effect without a save action",
        "storyId": "components-controls-switch--playground"
      },
      {
        "name": "Textarea",
        "slug": "textarea",
        "useFor": "Multi-line text input that auto-grows (field-sizing: content)",
        "storyId": "components-controls-textarea--playground"
      }
    ]
  },
  {
    "key": "content",
    "label": "Content",
    "blurb": "Shows what the screen already has, and arranges it",
    "items": [
      {
        "name": "Accordion",
        "slug": "accordion",
        "useFor": "Settings panels, filter groups, FAQ-style content",
        "storyId": "components-content-accordion--playground"
      },
      {
        "name": "AI Gradient Icon",
        "slug": "ai-gradient-icon",
        "useFor": "Marking something as Genie or AI — paints a DBUI icon with the brand gradient",
        "storyId": "components-content-ai-gradient-icon--playground"
      },
      {
        "name": "Aspect Ratio",
        "slug": "aspect-ratio",
        "useFor": "Lock image/video proportions inside cards and grids",
        "storyId": "components-content-aspect-ratio--playground"
      },
      {
        "name": "Avatar",
        "slug": "avatar",
        "useFor": "User identity (image, fallback initials, default icon)",
        "storyId": "components-content-avatar--playground"
      },
      {
        "name": "Breadcrumb",
        "slug": "breadcrumb",
        "useFor": "Hierarchical path back to root (last item is current page)",
        "storyId": "components-content-breadcrumb--playground"
      },
      {
        "name": "Card",
        "slug": "card",
        "useFor": "Bounded content surfaces with elevation (rounded-4, shadow)",
        "storyId": "components-content-card--playground"
      },
      {
        "name": "Code Block",
        "slug": "code-block",
        "useFor": "A block of code on its own — a query the agent wrote, a snippet in a doc, a preview tab",
        "storyId": "components-content-surfaces--code"
      },
      {
        "name": "Editor Tabs",
        "slug": "editor-tabs",
        "useFor": "Code-editor style closeable tabs with file-type icons",
        "storyId": "components-content-editortabs--playground"
      },
      {
        "name": "Key Value Pair",
        "slug": "key-value-pair",
        "useFor": "Metadata in detail panels and sidebars, key beside value by default",
        "storyId": "components-content-keyvaluepair--playground"
      },
      {
        "name": "Label",
        "slug": "label",
        "useFor": "The name of a form field",
        "storyId": "components-controls-label--playground"
      },
      {
        "name": "Metric Card",
        "slug": "metric-card",
        "useFor": "One metric, its shape and one way into the surface behind it — the overview card unit",
        "storyId": "components-content-metric-card--playground"
      },
      {
        "name": "Navbar",
        "slug": "navbar",
        "useFor": "Top-level product navigation (workspace switcher, global actions)",
        "storyId": "components-content-navbar--default"
      },
      {
        "name": "Pagination",
        "slug": "pagination",
        "useFor": "Paged tables with previous/next, ellipsis for large counts",
        "storyId": "components-content-pagination--playground"
      },
      {
        "name": "Schema Browser",
        "slug": "schema-browser",
        "useFor": "Reading a table's shape — columns, their types, which are keys",
        "storyId": "components-content-surfaces--schema"
      },
      {
        "name": "Separator",
        "slug": "separator",
        "useFor": "Visual divider between content groups",
        "storyId": "components-content-separator--playground"
      },
      {
        "name": "Stat Card",
        "slug": "stat-card",
        "useFor": "One headline total in a row of peers — the KPI band at the top of an overview",
        "storyId": "components-content-stat-card--playground"
      },
      {
        "name": "Table",
        "slug": "table",
        "useFor": "Structured data with sortable columns, row hover, optional row actions",
        "storyId": "components-content-table--playground"
      },
      {
        "name": "Tabs",
        "slug": "tabs",
        "useFor": "Switch between sibling content panels of equal importance (2–7 tabs)",
        "storyId": "components-content-tabs--playground"
      },
      {
        "name": "Tag",
        "slug": "tag",
        "useFor": "Removable filter chips, key:value labels in faceted filters",
        "storyId": "components-content-tag--playground"
      },
      {
        "name": "Terminal",
        "slug": "terminal",
        "useFor": "Command output a reader watches arrive — a build, a test run, a pipeline log",
        "storyId": "components-content-surfaces--command-output"
      },
      {
        "name": "Tree",
        "slug": "data-tree",
        "useFor": "Hierarchical data browsing (catalogs, schemas, tables) — every node has a typed icon",
        "storyId": "components-content-tree-data-tree--default"
      }
    ]
  },
  {
    "key": "chat",
    "label": "Chat",
    "blurb": "A turn in an agent conversation, or the trace behind one",
    "items": [
      {
        "name": "Artifact",
        "slug": "artifact",
        "useFor": "Something the agent produced that a reader can open — a notebook, a query, a dashboard",
        "storyId": "components-chat-interaction--outputs"
      },
      {
        "name": "Checkpoint",
        "slug": "checkpoint",
        "useFor": "A point in the thread a reader can return to",
        "storyId": "components-chat-interaction--outputs"
      },
      {
        "name": "Confirmation",
        "slug": "confirmation",
        "useFor": "A question the agent needs answered before it continues — approving a destructive step",
        "storyId": "components-chat-interaction--answering"
      },
      {
        "name": "Conversation",
        "slug": "conversation",
        "useFor": "The scrolling transcript — sticks to the latest turn while streaming, releases on scroll up",
        "storyId": "components-chat-thread--full-thread"
      },
      {
        "name": "Details",
        "slug": "details",
        "useFor": "Answering \"what is this asset\" in the thread — a table, model or dashboard the agent named",
        "storyId": "components-chat-details--playground"
      },
      {
        "name": "Message",
        "slug": "message",
        "useFor": "One turn. from=\"user\" is a filled box, from=\"assistant\" is flush body text",
        "storyId": "components-chat-thread--messages"
      },
      {
        "name": "Message Actions",
        "slug": "message-actions",
        "useFor": "The row that acts on an answer — copy, feedback, share, then Sources",
        "storyId": "components-chat-thread--sources-in-action-row"
      },
      {
        "name": "Message Thumbnail",
        "slug": "message-thumbnail",
        "useFor": "Media attached to a turn — a dropped image, a chart the agent produced",
        "storyId": "components-chat-thread--media-in-a-turn"
      },
      {
        "name": "Plan",
        "slug": "plan",
        "useFor": "The checklist the agent keeps across a long run — what is still left",
        "storyId": "components-chat-thread--plans"
      },
      {
        "name": "Prompt Input",
        "slug": "prompt-input",
        "useFor": "The composer. accent=\"ai\" for the Genie gradient border",
        "storyId": "components-chat-thread--composer"
      },
      {
        "name": "Queue",
        "slug": "queue",
        "useFor": "The state of work the agent is holding, in the rail — pending, running, done",
        "storyId": "components-chat-interaction--work-queue"
      },
      {
        "name": "Reasoning",
        "slug": "reasoning",
        "useFor": "The thinking trace — \"Thought for 40s\". With no children it is a live status row",
        "storyId": "components-chat-thread--reasoning-states"
      },
      {
        "name": "Response",
        "slug": "response",
        "useFor": "Every assistant answer — renders the markdown models emit, with zero dependencies",
        "storyId": "components-chat-thread--response-markdown"
      },
      {
        "name": "Sources",
        "slug": "sources",
        "useFor": "Naming what an answer drew on, inside MessageActions as its last child",
        "storyId": "components-chat-thread--sources-in-action-row"
      },
      {
        "name": "Suggestion",
        "slug": "suggestion",
        "useFor": "Next steps a reader may take or ignore, under the answer they follow from",
        "storyId": "components-chat-interaction--answering"
      },
      {
        "name": "Task",
        "slug": "task",
        "useFor": "One thing the agent did on its own — read a file, ran a query. Past tense, with the object",
        "storyId": "components-chat-thread--tasks"
      }
    ]
  },
  {
    "key": "feedback",
    "label": "Feedback",
    "blurb": "Reports what the system is doing or what just happened",
    "items": [
      {
        "name": "Alert",
        "slug": "alert",
        "useFor": "Persistent inline messages tied to page content (info / warning / danger / success)",
        "storyId": "components-overlays-alert--playground"
      },
      {
        "name": "Badge",
        "slug": "badge",
        "useFor": "Short status labels and counts (1–2 words)",
        "storyId": "components-content-badge--playground"
      },
      {
        "name": "Empty",
        "slug": "empty",
        "useFor": "Zero-data states with title, description, primary action",
        "storyId": "components-content-empty--playground"
      },
      {
        "name": "Progress Bar",
        "slug": "progress",
        "useFor": "Determinate progress with a known endpoint (percentage or step count)",
        "storyId": "components-content-progress--playground"
      },
      {
        "name": "Skeleton",
        "slug": "skeleton",
        "useFor": "Initial-load placeholders that match the shape of the incoming content",
        "storyId": "components-content-skeleton--playground"
      },
      {
        "name": "Spinner",
        "slug": "spinner",
        "useFor": "Indeterminate loading >1 s",
        "storyId": "components-content-spinner--playground"
      },
      {
        "name": "Status",
        "slug": "status",
        "useFor": "Status with icon + label (running, error, success, online, …)",
        "storyId": "components-content-status--playground"
      },
      {
        "name": "Toast",
        "slug": "sonner",
        "useFor": "Transient feedback toasts after an action (save, copy, delete)",
        "storyId": "components-overlays-toast--playground"
      }
    ]
  },
  {
    "key": "overlays",
    "label": "Overlays",
    "blurb": "Puts content above the page and takes focus with it",
    "items": [
      {
        "name": "Alert Dialog",
        "slug": "alert-dialog",
        "useFor": "Confirming destructive or irreversible actions",
        "storyId": "components-overlays-alertdialog--playground"
      },
      {
        "name": "Dialog",
        "slug": "dialog",
        "useFor": "Focused tasks and forms in an overlay (max one open at a time)",
        "storyId": "components-overlays-dialog--playground"
      },
      {
        "name": "Drawer",
        "slug": "drawer",
        "useFor": "Detail panels, settings, secondary content sliding in from the right",
        "storyId": "components-overlays-drawer--playground"
      },
      {
        "name": "Hover Card",
        "slug": "hover-card",
        "useFor": "Rich preview content on hover (user profiles, link previews)",
        "storyId": "components-overlays-hovercard--playground"
      },
      {
        "name": "Popover",
        "slug": "popover",
        "useFor": "Date pickers, color pickers, mini-forms, rich tooltips with content",
        "storyId": "components-overlays-popover--playground"
      },
      {
        "name": "Tooltip",
        "slug": "tooltip",
        "useFor": "One-line hover hints, especially on icon-only buttons (size=\"icon-md\")",
        "storyId": "components-overlays-tooltip--playground"
      }
    ]
  },
  {
    "key": "compositions",
    "label": "Compositions",
    "blurb": "Frames the page, so a screen takes it from a shell rather than building one",
    "items": [
      {
        "name": "Controls Bar",
        "slug": "controls-bar",
        "useFor": "Filter / search / sort row below PageHeader (Shell A list pages, etc.)",
        "storyId": "components-compositions-controls-bar--filters-only"
      },
      {
        "name": "Date Range",
        "slug": "date-range",
        "useFor": "Pair of start + end date fields (run history, audit windows, time-window filters)",
        "storyId": "components-controls-date-range--playground"
      },
      {
        "name": "Dropzone",
        "slug": "dropzone",
        "useFor": "A file upload target that accepts a drop and a click — ingestion, volume uploads",
        "storyId": "components-compositions-dropzone--playground"
      },
      {
        "name": "Page Header",
        "slug": "page-header",
        "useFor": "Top of every content surface — title row + optional Tabs row",
        "storyId": "components-compositions-page-header--title-only"
      },
      {
        "name": "Platform Header",
        "slug": "platform-header",
        "useFor": "The Databricks top bar (sidebar toggle, search, workspace, Genie, apps, profile)",
        "storyId": "components-compositions-platform-header--default"
      }
    ]
  },
  {
    "key": "viz",
    "label": "Viz",
    "blurb": "Encodes a number as length, angle, area or colour",
    "items": [
      {
        "name": "Bar Chart",
        "slug": "bar-chart",
        "useFor": "Counts or amounts across categories or time buckets; stacks when a datum has series",
        "storyId": "components-viz-charts--bars"
      },
      {
        "name": "Donut Chart",
        "slug": "donut-chart",
        "useFor": "A small part-to-whole split where the total matters (centerValue)",
        "storyId": "components-viz-charts--donut"
      },
      {
        "name": "Heatmap",
        "slug": "heatmap",
        "useFor": "One measure across two ordered axes — activity by day and four-hour window",
        "storyId": "components-viz-charts--heatmap-grid"
      },
      {
        "name": "Leaderboard",
        "slug": "leaderboard",
        "useFor": "Top-N rows where the bar length *is* the value and the label sits over the bar",
        "storyId": "components-viz-charts--leaderboard-rows"
      },
      {
        "name": "Legend",
        "slug": "legend",
        "useFor": "**Inner part.** A colour key with a value column, beside a chart that cannot draw its own",
        "storyId": "components-viz-charts--donut"
      },
      {
        "name": "Line Series",
        "slug": "line-series",
        "useFor": "A metric over time; drop the axes for an inline sparkline; multi-line when data has series",
        "storyId": "components-viz-charts--line"
      },
      {
        "name": "Segmented Bar",
        "slug": "segmented-bar",
        "useFor": "Part-to-whole in a single row — asset types, cost split, health mix (≤5 segments)",
        "storyId": "components-viz-charts--segmented"
      },
      {
        "name": "Treemap",
        "slug": "treemap",
        "useFor": "Two-level hierarchies sized by a metric — catalogs by schema size, cost by service",
        "storyId": "components-viz-charts--treemap-tiles"
      }
    ]
  }
]

export const galleryTotal = 79
