// Generated by scripts/generate-layout-data.mjs — do not edit by hand.
// Every value is read out of the file named beside it, so the Layout page
// cannot quote an inset, a width or a scroll owner the source does not have.

export type Region = {
  id: string
  label: string
  component: string
  file: string
  /** frame = present on every page · region = stacked inside the content surface */
  scope: "frame" | "region"
  classes: string[]
}

export type Panel = {
  id: string
  label: string
  edge: "left" | "right" | "bottom"
  component: string
  file: string
  holds: string
  width: string | null
  classes: string[]
}

export type ScrollOwner = {
  file: string
  classes: string
  /** bounded = capped by max-h, a menu · column = sized by its parent, owns one column */
  kind: "bounded" | "column"
}

export type Spacing = {
  tokenFamily: { name: string; tokens: number; live: boolean }
  utility: {
    name: string
    value: string | null
    resolvesTo: string | null
    origin: string
    uses: number
    files: number
  }
}

export const regions: Region[] = [
  {
    "id": "platform-header",
    "label": "Platform header",
    "component": "PlatformHeader",
    "file": "packages/dbui-shells/src/components/PlatformHeader.tsx",
    "scope": "frame",
    "classes": [
      "flex",
      "h-12",
      "shrink-0",
      "items-center",
      "px-3"
    ]
  },
  {
    "id": "product-nav",
    "label": "Product nav",
    "component": "PlatformNav",
    "file": "packages/dbui-shells/src/components/PlatformNav.tsx",
    "scope": "frame",
    "classes": [
      "w-[180px]",
      "shrink-0",
      "overflow-y-auto",
      "px-3",
      "py-1"
    ]
  },
  {
    "id": "content-surface",
    "label": "Content surface",
    "component": "Base",
    "file": "packages/dbui-shells/src/shells/Base.tsx",
    "scope": "frame",
    "classes": [
      "flex-1",
      "min-w-0",
      "min-h-0",
      "overflow-y-auto",
      "border-border-base"
    ]
  },
  {
    "id": "page-header",
    "label": "Page header",
    "component": "PageHeader",
    "file": "packages/dbui/src/components/ui/page-header.tsx",
    "scope": "region",
    "classes": [
      "flex",
      "items-center",
      "justify-between",
      "gap-2",
      "px-4",
      "py-2"
    ]
  },
  {
    "id": "controls-bar",
    "label": "Controls bar",
    "component": "ControlsBar",
    "file": "packages/dbui/src/components/ui/controls-bar.tsx",
    "scope": "region",
    "classes": [
      "flex",
      "items-center",
      "justify-between",
      "gap-2",
      "px-4",
      "py-2"
    ]
  }
]

export const panels: Panel[] = [
  {
    "id": "product-nav",
    "label": "Product nav",
    "edge": "left",
    "component": "PlatformNav",
    "file": "packages/dbui-shells/src/components/PlatformNav.tsx",
    "holds": "Where you are in the product",
    "width": "w-[180px]",
    "classes": [
      "w-[180px]",
      "shrink-0",
      "overflow-y-auto",
      "px-3",
      "py-1"
    ]
  },
  {
    "id": "tree-rail",
    "label": "Tree rail",
    "edge": "left",
    "component": "CatalogTree",
    "file": "packages/dbui-shells/src/shells/CatalogExplorer.tsx",
    "holds": "Where you are inside one hierarchy",
    "width": "w-[280px]",
    "classes": [
      "flex",
      "w-[280px]",
      "shrink-0",
      "flex-col",
      "border-r",
      "border-border-base"
    ]
  },
  {
    "id": "assistant",
    "label": "Assistant panel",
    "edge": "right",
    "component": "AssistantPanel",
    "file": "packages/dbui-shells/src/components/AssistantPanel.tsx",
    "holds": "A conversation about what is on screen",
    "width": "w-[360px]",
    "classes": [
      "flex",
      "w-[360px]",
      "shrink-0",
      "flex-col",
      "border-border-base"
    ]
  }
]

export const scrollOwners: ScrollOwner[] = [
  {
    "file": "packages/dbui-shells/src/components/FacetedFilter.tsx",
    "classes": "max-h-56 overflow-y-auto p-1 pt-0",
    "kind": "bounded"
  },
  {
    "file": "packages/dbui-shells/src/components/PlatformNav.tsx",
    "classes": "overflow-y-auto",
    "kind": "column"
  },
  {
    "file": "packages/dbui-shells/src/components/PlatformNav.tsx",
    "classes": "w-[180px] shrink-0 overflow-y-auto px-3 py-1",
    "kind": "column"
  },
  {
    "file": "packages/dbui-shells/src/components/SearchPopup.tsx",
    "classes": "max-h-[320px] overflow-y-auto",
    "kind": "bounded"
  },
  {
    "file": "packages/dbui-shells/src/compositions/DataTreeExplorer.tsx",
    "classes": "flex-1 overflow-y-auto px-1 pb-4",
    "kind": "column"
  },
  {
    "file": "packages/dbui-shells/src/compositions/FileTreeExplorer.tsx",
    "classes": "flex-1 overflow-y-auto px-1 pb-4",
    "kind": "column"
  },
  {
    "file": "packages/dbui-shells/src/shells/Base.tsx",
    "classes": "flex-1 min-w-0 min-h-0 overflow-y-auto border-border-base",
    "kind": "column"
  },
  {
    "file": "packages/dbui-shells/src/shells/CatalogExplorer.tsx",
    "classes": "flex-1 overflow-y-auto px-1 pb-4",
    "kind": "column"
  },
  {
    "file": "packages/dbui-shells/src/shells/CatalogExplorer.tsx",
    "classes": "flex-1 min-w-0 overflow-y-auto",
    "kind": "column"
  }
]

/** The app frame. `scrolls: false` is what makes every rule below hold. */
export const frame: { file: string; classes: string[]; scrolls: boolean } = {
  "file": "packages/dbui-shells/src/shells/Base.tsx",
  "classes": [
    "flex",
    "h-screen",
    "flex-col",
    "overflow-hidden"
  ],
  "scrolls": false
}

export const spacing: Spacing = {
  "tokenFamily": {
    "name": "--db-space-*",
    "tokens": 9,
    "live": true
  },
  "utility": {
    "name": "--spacing",
    "value": "0.25rem",
    "resolvesTo": "calc(var(--db-spacing-unit) * var(--db-density-scalar))",
    "origin": "override",
    "uses": 819,
    "files": 78
  }
}

/** What `dbui-shells` exports today, against the shells composition.md defines. */
export const shellModules: string[] = [
  "Base",
  "CatalogLanding",
  "CatalogLayout",
  "CatalogTree",
  "DataTreeExplorer",
  "FileTreeExplorer",
  "PreviewPopup"
]
