// Generated by scripts/generate-shell-data.mjs — do not edit by hand.
// Source: packages/dbui/composition.md, via the CLI API.

export type Shell = {
  id: string
  name: string
  purpose: string
  regions: string[]
  scaling: string
  scroll: string
}

export const shells: Shell[] = [
  {
    "id": "A",
    "name": "List page",
    "purpose": "flat collections (Dashboards, Queries, Jobs, Pipelines, Notebooks, Clusters, Alerts, Warehouses)",
    "regions": [
      "Page header (<PageHeader> + <PageHeaderTitle> + <PageHeaderActions>) — single horizontal row, title left, primary action(s) right",
      "Tabs (optional, sibling of <PageHeader>) — only for sibling variants (Dashboards / Legacy dashboards)",
      "Featured band (optional) — promoted content card grid inside a bg-surface-subtle inset",
      "Controls bar (<ControlsBar> + <ControlsBarFilters> + <ControlsBarActions>) — filter/search/sort row, sibling",
      "Table — paginated, first column always entity name, trailing overflow menu"
    ],
    "scaling": "full-width content, single column. All regions stretch horizontally.",
    "scroll": "the content container scrolls; header row and control bar may be sticky."
  },
  {
    "id": "B",
    "name": "Data Tree + Detail (Catalog Explorer)",
    "purpose": "hierarchical data entities (Catalogs → Schemas → Tables / Volumes / Models)",
    "regions": [
      "Data tree rail — <DataTreeView> wrapped in a tree panel",
      "Detail surface — flex-1"
    ],
    "scaling": "tree rail fixed/resizable; detail surface fills remainder. Below 1024px, rail collapses to icon-only (hover-to-peek) and detail takes near-full width.",
    "scroll": "tree and detail scroll independently."
  },
  {
    "id": "C",
    "name": "File Tree + List (Workspace Browser)",
    "purpose": "user-mutable hierarchies (Workspace, Repos, user folders)",
    "regions": [
      "File tree rail — <FileTreeView>",
      "Detail surface — list of the current folder's contents"
    ],
    "scaling": "same as Shell B.",
    "scroll": "same as Shell B."
  },
  {
    "id": "D",
    "name": "Editor (SQL Editor, Notebook, Pipeline editor)",
    "purpose": "code/query authoring with live output",
    "regions": [
      "Tool rail — 44px, icon-only tool switcher",
      "Tool panel — 260px, content of the active tool (Data tree, File tree, Variables, Connections, …)",
      "Editor surface — vertically split:",
      "- **Top:** tab bar + editor toolbar + code editor",
      "- **Bottom:** output panel (resizable, dismissible)"
    ],
    "scaling": "- Tool rail fixed at 44px (never collapses)\n- Tool panel behaves like a tree rail (200–400px, hides at ≤1024px)\n- Editor/output split: default 60/40 vertical; resizable via drag handle between them\n- Output collapses to minimum height when dismissed, tab bar retains quick-reopen control",
    "scroll": "- Tool panel scrolls internally\n- Editor surface scrolls within its pane\n- Output table scrolls within the output pane\n- **No page-level scroll** — the editor's internal panes absorb all scrolling"
  },
  {
    "id": "E",
    "name": "Asset Detail",
    "purpose": "detail view of a single entity (table, volume, model, schema, dashboard, query)",
    "regions": [
      "Breadcrumb — Browse › catalog › schema › entity, right-side copy-path button",
      "Title row — entity type icon · name · qualifiers · action buttons",
      "Sub-tabs — Overview (default) / Columns / Details / Permissions / History / Lineage / Insights / Quality",
      "Body — two columns:",
      "- Main content (flex-1) — tab-dependent",
      "- Metadata sidebar (280px, sticky) — <KeyValuePair> sections separated by <Separator>"
    ],
    "scaling": "- Metadata sidebar hides at ≤1280px; accessible via a toggle that slides it in as an overlay\n- Main content min-width 640px before sidebar is forced to hide\n- Sub-tabs horizontally scroll if they exceed container width (rare — usually <8)",
    "scroll": "- Main content scrolls\n- Sidebar scrolls independently, sticky top"
  }
]
