// Generated by scripts/generate-utility-data.mjs — do not edit by hand.
// Sources: packages/dbui/src/lib/, packages/dbui/src/tokens/*.css, packages/dbui/src/index.ts

export type UtilityExport = { name: string; kind: string; signature: string }

export type UtilityModule = {
  module: string
  importPath: string
  inBarrel: boolean
  exports: UtilityExport[]
}

export type CssUtility = { name: string; source: string; declarations: string[] }

export const utilityModules: UtilityModule[] = [
  {
    "module": "lib/button-variants",
    "importPath": "dbui/lib/button-variants",
    "inBarrel": true,
    "exports": [
      {
        "name": "buttonVariants",
        "kind": "const",
        "signature": "buttonVariants"
      }
    ]
  },
  {
    "module": "lib/cva",
    "importPath": "dbui/lib/cva",
    "inBarrel": false,
    "exports": [
      {
        "name": "VariantProps",
        "kind": "type",
        "signature": "VariantProps<T extends (...args: any) => any>"
      },
      {
        "name": "cva",
        "kind": "function",
        "signature": "cva<T extends ConfigSchema>(base?: ClassValue, config?: Config<T>)"
      }
    ]
  },
  {
    "module": "lib/utils",
    "importPath": "dbui/lib/utils",
    "inBarrel": true,
    "exports": [
      {
        "name": "ClassValue",
        "kind": "type",
        "signature": "ClassValue"
      },
      {
        "name": "cn",
        "kind": "function",
        "signature": "cn(...inputs: ClassValue[]): string"
      }
    ]
  }
]

/** Documented on the Tokens page, where the ramp they come from is rendered. */
export const rampUtilities: string[] = [
  "type-hint",
  "type-eyebrow",
  "type-label",
  "type-label-bold",
  "type-body",
  "type-body-bold",
  "type-code",
  "type-block",
  "type-paragraph",
  "type-paragraph-bold",
  "type-title-4",
  "type-title-3",
  "type-title-2",
  "type-title-1"
]

export const cssUtilities: CssUtility[] = [
  {
    "name": "no-scrollbar",
    "source": "tokens/globals.css",
    "declarations": [
      "-ms-overflow-style: none;",
      "scrollbar-width: none;",
      "&::-webkit-scrollbar { display: none; }"
    ]
  }
]
