/**
 * dbui_render_react_preview
 *
 * Writes a JSX snippet to a temp Storybook story file in
 * apps/portal/src/stories/_preview/, returning the URL the user can open
 * in a browser to see it rendered.
 *
 * For full agent autonomy (auto-screenshot, auto-compare), drop in
 * puppeteer-core or playwright when network access permits — see
 * packages/dbui-mcp/docs/iteration-loops.md for the wiring.
 *
 * Today: writes the file, returns a URL + optionally a path the user can
 * open. The agent then asks the user to drop the screenshot back, OR
 * the agent can move on with the structural lint result alone.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const REPO = path.resolve(__dirname, "../../../..")
const PREVIEW_DIR = path.join(REPO, "apps/portal/src/stories/_preview")

export const tool = {
  name: "dbui_render_react_preview",
  description:
    "Take a React/TSX snippet, write it to a temp Storybook story in apps/portal/src/stories/_preview/, and return the Storybook URL the user can open. Use this when you want a visual rendering of generated code — the user opens the URL, screenshots, drops it back; you compare to the source design and revise. After the iteration is done, call cleanup=true to remove the temp file.",
  inputSchema: {
    type: "object",
    properties: {
      code: {
        type: "string",
        description: "The JSX/TSX snippet to render. Must export the component as default OR be self-contained JSX (will be wrapped automatically).",
      },
      name: {
        type: "string",
        description: "Story name. Becomes the filename and Storybook entry. Default 'Preview'.",
        default: "Preview",
      },
      cleanup: {
        type: "boolean",
        description: "If true, removes a previously-written preview file with the same name. Use this once the iteration is done.",
        default: false,
      },
      imports: {
        type: "array",
        items: { type: "string" },
        description: "Optional extra import statements to inject above the snippet (e.g. ['import { Button } from \"@muditmittal/dbui/components/ui/button\"']).",
      },
    },
    required: ["code"],
  },
}

function ensureDir() {
  if (!fs.existsSync(PREVIEW_DIR)) fs.mkdirSync(PREVIEW_DIR, { recursive: true })
}

function safeName(name) {
  return name.replace(/[^A-Za-z0-9]/g, "")
}

function buildStoryFile({ name, code, imports = [] }) {
  const safe = safeName(name) || "Preview"
  // Detect if user already wrote a default export
  const hasExport = /export\s+default\s+/.test(code)
  let body
  if (hasExport) {
    body = code
  } else {
    body = `export default function ${safe}() {\n  return (\n    ${code.trim()}\n  )\n}`
  }

  const importLines = (imports || []).join("\n")

  return `// AUTO-GENERATED by dbui_render_react_preview — safe to delete
import type { Meta, StoryObj } from "@storybook/react"
${importLines}

${body.replace(/^export\s+default\s+function\s+\w+/, `function _${safe}_Component`).replace(/^export\s+default\s+/, "const _" + safe + "_Component = ")}

const meta = {
  title: "_Preview/${safe}",
  component: _${safe}_Component as any,
  parameters: { layout: "centered" },
} satisfies Meta<any>
export default meta

export const Default: StoryObj = {}
`
}

export function run({ code, name = "Preview", cleanup = false, imports = [] }) {
  ensureDir()
  const safe = safeName(name) || "Preview"
  const filePath = path.join(PREVIEW_DIR, `${safe}.stories.tsx`)
  const url = `http://localhost:6006/?path=/story/_preview-${safe.toLowerCase()}--default`
  const fileRel = path.relative(REPO, filePath)

  if (cleanup) {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath)
      return { ok: true, removed: fileRel, message: `Cleaned up ${fileRel}.` }
    }
    return { ok: true, message: `Nothing to clean up (no file at ${fileRel}).` }
  }

  const story = buildStoryFile({ name: safe, code, imports })
  fs.writeFileSync(filePath, story)

  return {
    ok: true,
    file: fileRel,
    storybookUrl: url,
    instructions: [
      `1. Wrote the story to ${fileRel}.`,
      `2. If Storybook is already running, the dev server will hot-reload. Otherwise: \`yarn workspace portal storybook\` (port 6006).`,
      `3. Open the URL: ${url}`,
      `4. Take a screenshot of the rendered output and drop it back into the conversation.`,
      `5. The agent will compare it to the source design and revise.`,
      `6. When done, call this tool again with cleanup: true and the same name.`,
    ],
    nextStep: "Once you have the screenshot, share it and ask the agent to compare against the source design.",
    autonomyNote: "For fully-autonomous render+compare without a human screenshot step, install puppeteer-core (~50MB) and re-deploy this tool. See packages/dbui-mcp/docs/iteration-loops.md.",
  }
}
