#!/usr/bin/env node
/**
 * Generates the data behind the Components gallery.
 *
 * The gallery must never be a hand-maintained list — it is the public claim
 * about what the library contains, so it is derived from the same CLI API that
 * agents read. Run after adding, renaming or recategorising a component.
 *
 *   node scripts/generate-gallery.mjs
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { componentList } from "../packages/dbui-cli/src/api.mjs"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const STORIES = path.join(ROOT, "apps/portal/src/stories")
const OUT = path.join(STORIES, "components/gallery-data.ts")

/** Storybook's own id algorithm, so generated links match the live index. */
const sanitize = (s) =>
  s
    .toLowerCase()
    .replace(/[ '’–—―′¿`~!@#$%^&*()_|+\-=?;:",.<>{}[\]\\/]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")

const storyId = (title, name) => `${sanitize(title)}--${sanitize(name)}`

/** Collect every story title in the Components root, keyed by its leaf name. */
function indexStories() {
  const found = new Map()
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        walk(p)
        continue
      }
      if (!entry.name.endsWith(".stories.tsx")) continue
      const src = fs.readFileSync(p, "utf8")
      const title = src.match(/title:\s*"([^"]+)"/)?.[1]
      if (!title || !title.startsWith("Components/")) continue
      // Prefer Playground; fall back to the first exported story.
      const names = [...src.matchAll(/export const (\w+):\s*StoryObj/g)].map((m) => m[1])
      const story = names.includes("Playground") ? "Playground" : names[0]
      if (!story) continue
      const leaf = title.split("/").pop()
      found.set(leaf.toLowerCase().replace(/[^a-z0-9]/g, ""), {
        title,
        id: storyId(title, story),
      })
    }
  }
  walk(STORIES)
  return found
}

/** Component-index names whose story lives under a different label. */
const ALIASES = {
  tree: "datatree",
  progressbar: "progress",
  radio: "radiogroup",
  togglebutton: "toggle",
  chart: "charts",
}

const normalise = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "")

/** Category display order — action-first, matching how a builder reaches for them. */
const ORDER = [
  ["action", "Action"],
  ["input", "Input"],
  ["selection", "Selection"],
  ["menu", "Menu"],
  ["overlay", "Overlay"],
  ["navigation", "Navigation"],
  ["feedback", "Feedback"],
  ["display", "Display"],
  ["layout", "Layout"],
  ["chrome", "Chrome"],
]

const stories = indexStories()
const { categories } = componentList().data

const groups = []
let linked = 0
let unlinked = 0

const seen = new Set()
const emit = (key, label) => {
  const items = categories[key]
  if (!items?.length) return
  seen.add(key)
  const entries = items
    // Internal primitives and deliberately-excluded aliases are real parts of
    // the codebase, but they are not things a builder browses for.
    .filter((c) => !/utility|internal|excluded|deprioriti/i.test(c.name))
    .map((c) => {
      // The index annotates names in parentheses; the gallery shows the name only.
      const name = c.name.replace(/\s*\(.*\)\s*$/, "").trim()
      const key = normalise(name)
      const match = stories.get(ALIASES[key] ?? key) ?? stories.get(key)
      if (match) linked++
      else unlinked++
      return {
        name,
        slug: c.slug,
        // The index is markdown; the gallery renders as plain text.
        useFor: (c.useFor || "").replace(/`/g, "").trim(),
        storyId: match?.id ?? null,
      }
    })
    .sort((a, b) => a.name.localeCompare(b.name))
  if (entries.length) groups.push({ key, label, items: entries })
}

for (const [key, label] of ORDER) emit(key, label)
for (const key of Object.keys(categories)) {
  if (!seen.has(key)) emit(key, key.charAt(0).toUpperCase() + key.slice(1))
}

const total = groups.reduce((n, g) => n + g.items.length, 0)

const file = `// Generated by scripts/generate-gallery.mjs — do not edit by hand.
// Source of truth: packages/dbui-cli/src/api.mjs (listComponents).

export type GalleryItem = {
  name: string
  slug: string
  useFor: string
  storyId: string | null
}

export type GalleryGroup = {
  key: string
  label: string
  items: GalleryItem[]
}

export const galleryGroups: GalleryGroup[] = ${JSON.stringify(groups, null, 2)}

export const galleryTotal = ${total}
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, file)

console.log(`wrote ${path.relative(ROOT, OUT)}`)
console.log(`  ${groups.length} categories, ${total} components`)
console.log(`  ${linked} linked to a story, ${unlinked} without one`)
if (unlinked) {
  const missing = groups.flatMap((g) => g.items.filter((i) => !i.storyId).map((i) => i.name))
  console.log(`  missing stories: ${missing.join(", ")}`)
}
