/**
 * GENERATED by scripts/generate-token-data.mjs — do not hand-edit.
 * Source: packages/dbui/src/tokens/theme.config.mjs `themes`.
 *
 * The aesthetics the system renders in. A theme varies token VALUES and never
 * token names, so switching one repaints the page without re-rendering a single
 * component — the same property that makes the color mode a one-class toggle.
 *
 * Mode and the density/type dials are separate axes and compose with this one.
 * A theme block declares only the tokens it moves, so switching theme cannot
 * disturb a mode, a scale, or a density scalar set on a subtree.
 */

export type ThemeMeta = {
  /** What goes in the attribute. */
  name: string
  label: string
  description: string
  /** Also emitted into `:root`, so it is the one the attribute never spells. */
  isDefault: boolean
}

/** Set on any element to theme that subtree; two themes can share one page. */
export const themeAttribute = "data-theme"

/** What a document that sets no attribute renders as. */
export const themeDefault = "core"

export const themes: ThemeMeta[] = [
  {
    "name": "core",
    "label": "Core",
    "description": "The system's own aesthetic. Neutral chrome, Figtree, pill controls.",
    "isDefault": true
  },
  {
    "name": "dubois",
    "label": "DuBois",
    "description": "The legacy product aesthetic. Blue primary, SF Pro, 4px controls.",
    "isDefault": false
  },
  {
    "name": "one",
    "label": "One",
    "description": "Warm neutrals, DM Sans, brand orange accent. Core's shapes.",
    "isDefault": false
  }
]
