// Generated by scripts/generate-token-data.mjs — do not edit by hand.
// Parsed from packages/dbui/src/tokens/tokens.css, so this is exactly what ships.

export type Token = { name: string; value: string }
export type ColorToken = { name: string; light: string; dark: string }
export type ColorGroup = { key: string; label: string; blurb: string; tokens: ColorToken[] }

export const colorGroups: ColorGroup[] = [
  {
    "key": "surface",
    "label": "Surface",
    "blurb": "Backgrounds. Every surface has a text colour that belongs on it.",
    "tokens": [
      {
        "name": "surface-base",
        "light": "#FFFFFF",
        "dark": "#11171C"
      },
      {
        "name": "surface-subtle",
        "light": "#FAFAFA",
        "dark": "#1F272D"
      },
      {
        "name": "surface-strong",
        "light": "#F5F5F5",
        "dark": "#2B343D"
      },
      {
        "name": "surface-inverse",
        "light": "#171717",
        "dark": "#F6F7F9"
      },
      {
        "name": "surface-accent",
        "light": "#D7EDFE",
        "dark": "#021E38"
      },
      {
        "name": "surface-inset",
        "light": "rgba(0, 0, 0, 0.08)",
        "dark": "rgba(255, 255, 255, 0.08)"
      },
      {
        "name": "surface-disabled",
        "light": "rgba(0, 0, 0, 0.12)",
        "dark": "rgba(255, 255, 255, 0.12)"
      }
    ]
  },
  {
    "key": "text",
    "label": "Text",
    "blurb": "Foreground colours. Base is the default, subtle steps back, inverse sits on dark surfaces.",
    "tokens": [
      {
        "name": "text-base",
        "light": "#262626",
        "dark": "#E8ECF0"
      },
      {
        "name": "text-strong",
        "light": "#171717",
        "dark": "#FFFFFF"
      },
      {
        "name": "text-subtle",
        "light": "#525252",
        "dark": "#92A4B3"
      },
      {
        "name": "text-inverse",
        "light": "#FFFFFF",
        "dark": "#11171C"
      },
      {
        "name": "text-disabled",
        "light": "rgba(0, 0, 0, 0.38)",
        "dark": "rgba(255, 255, 255, 0.38)"
      },
      {
        "name": "text-accent",
        "light": "#0E538B",
        "dark": "#8ACAFF"
      }
    ]
  },
  {
    "key": "action",
    "label": "Action",
    "blurb": "Interactive fills and their labels. Hover and press are separate stops, not opacity tricks.",
    "tokens": [
      {
        "name": "action-default-base",
        "light": "#FAFAFA",
        "dark": "#1F272D"
      },
      {
        "name": "action-default-hover",
        "light": "rgba(0, 0, 0, 0.06)",
        "dark": "rgba(255, 255, 255, 0.08)"
      },
      {
        "name": "action-default-press",
        "light": "rgba(0, 0, 0, 0.1)",
        "dark": "rgba(255, 255, 255, 0.12)"
      },
      {
        "name": "action-primary-base",
        "light": "#171717",
        "dark": "#D1D9E1"
      },
      {
        "name": "action-primary-hover",
        "light": "rgba(23, 23, 23, 0.9)",
        "dark": "rgba(209, 217, 225, 0.9)"
      },
      {
        "name": "action-primary-press",
        "light": "rgba(23, 23, 23, 0.8)",
        "dark": "rgba(209, 217, 225, 0.8)"
      },
      {
        "name": "action-selected-base",
        "light": "rgba(0, 0, 0, 0.06)",
        "dark": "rgba(255, 255, 255, 0.08)"
      },
      {
        "name": "action-selected-hover",
        "light": "rgba(0, 0, 0, 0.1)",
        "dark": "rgba(255, 255, 255, 0.12)"
      },
      {
        "name": "action-selected-press",
        "light": "rgba(0, 0, 0, 0.14)",
        "dark": "rgba(255, 255, 255, 0.16)"
      },
      {
        "name": "action-positive-base",
        "light": "#277C43",
        "dark": "#3BA65E"
      },
      {
        "name": "action-positive-hover",
        "light": "#115026",
        "dark": "#8DDDA8"
      },
      {
        "name": "action-positive-press",
        "light": "#093919",
        "dark": "#B1ECC5"
      },
      {
        "name": "action-negative-base",
        "light": "#C82D4C",
        "dark": "#E65B77"
      },
      {
        "name": "action-negative-hover",
        "light": "#9E102C",
        "dark": "#F792A6"
      },
      {
        "name": "action-negative-press",
        "light": "#630316",
        "dark": "#FBD0D8"
      },
      {
        "name": "action-label-base",
        "light": "#262626",
        "dark": "#F6F7F9"
      },
      {
        "name": "action-label-hover",
        "light": "#171717",
        "dark": "#FFFFFF"
      },
      {
        "name": "action-label-press",
        "light": "#000000",
        "dark": "#FFFFFF"
      },
      {
        "name": "action-label-inverse-base",
        "light": "#FFFFFF",
        "dark": "#11171C"
      },
      {
        "name": "action-label-inverse-hover",
        "light": "rgba(255, 255, 255, 0.8)",
        "dark": "rgba(0, 0, 0, 0.8)"
      },
      {
        "name": "action-label-inverse-press",
        "light": "rgba(255, 255, 255, 0.7)",
        "dark": "rgba(0, 0, 0, 0.7)"
      }
    ]
  },
  {
    "key": "border",
    "label": "Border",
    "blurb": "Decorative dividers and outlines. Form controls use the separate input-border set.",
    "tokens": [
      {
        "name": "border-width-none",
        "light": "0px",
        "dark": "0px"
      },
      {
        "name": "border-width-thin",
        "light": "1px",
        "dark": "1px"
      },
      {
        "name": "border-width-thick",
        "light": "2px",
        "dark": "2px"
      },
      {
        "name": "border-base",
        "light": "#E5E5E5",
        "dark": "rgba(255, 255, 255, 0.1)"
      },
      {
        "name": "border-strong",
        "light": "#D4D4D4",
        "dark": "rgba(255, 255, 255, 0.15)"
      },
      {
        "name": "border-subtle",
        "light": "#F5F5F5",
        "dark": "rgba(255, 255, 255, 0.06)"
      },
      {
        "name": "border-inverse",
        "light": "#404040",
        "dark": "#C0CDD8"
      },
      {
        "name": "border-disabled",
        "light": "rgba(0, 0, 0, 0.12)",
        "dark": "rgba(255, 255, 255, 0.12)"
      },
      {
        "name": "border-accent",
        "light": "#2272B4",
        "dark": "#4299E0"
      }
    ]
  },
  {
    "key": "input-border",
    "label": "Input border",
    "blurb": "Form control borders — darker than decorative borders so fields read as editable.",
    "tokens": [
      {
        "name": "input-border-base",
        "light": "#E5E5E5",
        "dark": "rgba(255, 255, 255, 0.15)"
      },
      {
        "name": "input-border-hover",
        "light": "#A3A3A3",
        "dark": "#8396A5"
      },
      {
        "name": "input-border-focus",
        "light": "#171717",
        "dark": "#D1D9E1"
      }
    ]
  },
  {
    "key": "status",
    "label": "Status",
    "blurb": "Positive, negative, warning and info, each with a surface, a border and a text colour.",
    "tokens": [
      {
        "name": "status-surface-info",
        "light": "#F0F8FF",
        "dark": "#021E38"
      },
      {
        "name": "status-surface-negative",
        "light": "#FFF5F7",
        "dark": "#3A010B"
      },
      {
        "name": "status-surface-positive",
        "light": "#F3FCF6",
        "dark": "#04220E"
      },
      {
        "name": "status-surface-warning",
        "light": "#FFF9EB",
        "dark": "#381001"
      },
      {
        "name": "status-border-info",
        "light": "#0E538B",
        "dark": "#4299E0"
      },
      {
        "name": "status-border-negative",
        "light": "#9E102C",
        "dark": "#E65B77"
      },
      {
        "name": "status-border-positive",
        "light": "#3BA65E",
        "dark": "#3BA65E"
      },
      {
        "name": "status-border-warning",
        "light": "#DE7921",
        "dark": "#DE7921"
      },
      {
        "name": "status-text-info",
        "light": "#2272B4",
        "dark": "#8ACAFF"
      },
      {
        "name": "status-text-negative",
        "light": "#C82D4C",
        "dark": "#F792A6"
      },
      {
        "name": "status-text-positive",
        "light": "#277C43",
        "dark": "#8DDDA8"
      },
      {
        "name": "status-text-warning",
        "light": "#BE501E",
        "dark": "#F2BE88"
      }
    ]
  },
  {
    "key": "link",
    "label": "Link",
    "blurb": "Link states. Visited is separate so long documents stay navigable.",
    "tokens": [
      {
        "name": "link-base",
        "light": "#2272B4",
        "dark": "#8ACAFF"
      },
      {
        "name": "link-hover",
        "light": "#0E538B",
        "dark": "#BAE1FC"
      },
      {
        "name": "link-press",
        "light": "#04355D",
        "dark": "#D7EDFE"
      },
      {
        "name": "link-visited",
        "light": "#04355D",
        "dark": "#D7EDFE"
      }
    ]
  },
  {
    "key": "focus",
    "label": "Focus",
    "blurb": "The focus ring and its offset. Never suppress these.",
    "tokens": [
      {
        "name": "focus-ring",
        "light": "#171717",
        "dark": "#D1D9E1"
      },
      {
        "name": "focus-ring-offset",
        "light": "#FFFFFF",
        "dark": "#11171C"
      }
    ]
  },
  {
    "key": "viz",
    "label": "Data visualisation",
    "blurb": "Categorical for unordered series, sequential for ordered magnitude.",
    "tokens": [
      {
        "name": "viz-categorical-1",
        "light": "#9575CD",
        "dark": "#8555C9"
      },
      {
        "name": "viz-categorical-2",
        "light": "#FFD54F",
        "dark": "#BD7C30"
      },
      {
        "name": "viz-categorical-3",
        "light": "#6CD7D2",
        "dark": "#2C8985"
      },
      {
        "name": "viz-categorical-4",
        "light": "#F06292",
        "dark": "#A11E4E"
      },
      {
        "name": "viz-categorical-5",
        "light": "#D4E157",
        "dark": "#9E9D00"
      },
      {
        "name": "viz-categorical-6",
        "light": "#A1887F",
        "dark": "#A8796D"
      },
      {
        "name": "viz-categorical-7",
        "light": "#90A0E0",
        "dark": "#4E62BA"
      },
      {
        "name": "viz-categorical-8",
        "light": "#EF9B80",
        "dark": "#CC471F"
      },
      {
        "name": "viz-categorical-9",
        "light": "#96BEB5",
        "dark": "#217766"
      },
      {
        "name": "viz-categorical-10",
        "light": "#AD6DAD",
        "dark": "#97409A"
      },
      {
        "name": "viz-sequential-1",
        "light": "#E8ECF0",
        "dark": "#0A2C36"
      },
      {
        "name": "viz-sequential-2",
        "light": "#D2F1FC",
        "dark": "#084150"
      },
      {
        "name": "viz-sequential-3",
        "light": "#A5E5F9",
        "dark": "#085B6E"
      },
      {
        "name": "viz-sequential-4",
        "light": "#65D3F4",
        "dark": "#0F7B95"
      },
      {
        "name": "viz-sequential-5",
        "light": "#22BFE5",
        "dark": "#169DBD"
      },
      {
        "name": "viz-sequential-6",
        "light": "#169DBD",
        "dark": "#22BFE5"
      },
      {
        "name": "viz-sequential-7",
        "light": "#0F7B95",
        "dark": "#65D3F4"
      },
      {
        "name": "viz-sequential-8",
        "light": "#085B6E",
        "dark": "#A5E5F9"
      },
      {
        "name": "viz-sequential-9",
        "light": "#084150",
        "dark": "#D2F1FC"
      },
      {
        "name": "viz-sequential-10",
        "light": "#0A2C36",
        "dark": "#F6F7F9"
      }
    ]
  },
  {
    "key": "utility",
    "label": "Utility",
    "blurb": "Scrim and skeleton — surfaces that exist only to obscure or stand in.",
    "tokens": [
      {
        "name": "utility-scrim",
        "light": "rgba(0, 0, 0, 0.72)",
        "dark": "rgba(0, 0, 0, 0.85)"
      },
      {
        "name": "utility-surface-skeleton",
        "light": "rgba(0, 0, 0, 0.12)",
        "dark": "rgba(255, 255, 255, 0.12)"
      },
      {
        "name": "utility-text-skeleton",
        "light": "rgba(0, 0, 0, 0.2)",
        "dark": "rgba(255, 255, 255, 0.2)"
      }
    ]
  }
]

export const space: Token[] = [
  {
    "name": "space-0",
    "value": "0"
  },
  {
    "name": "space-3xs",
    "value": "calc(var(--db-spacing-unit) * 0.5 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-2xs",
    "value": "calc(var(--db-spacing-unit) * 1 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-xs",
    "value": "calc(var(--db-spacing-unit) * 2 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-sm",
    "value": "calc(var(--db-spacing-unit) * 3 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-md",
    "value": "calc(var(--db-spacing-unit) * 4 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-lg",
    "value": "calc(var(--db-spacing-unit) * 6 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-xl",
    "value": "calc(var(--db-spacing-unit) * 8 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  },
  {
    "name": "space-2xl",
    "value": "calc(var(--db-spacing-unit) * 12 * var(--db-spacing-scalar) * var(--db-density-scalar))"
  }
]

export const spaceInline: Token[] = [
  {
    "name": "space-inline-xs",
    "value": "0.25em"
  },
  {
    "name": "space-inline-sm",
    "value": "0.5em"
  }
]

export const radius: Token[] = [
  {
    "name": "radius-sm",
    "value": "0.25rem"
  },
  {
    "name": "radius-md",
    "value": "0.5rem"
  },
  {
    "name": "radius-lg",
    "value": "0.75rem"
  },
  {
    "name": "radius-xl",
    "value": "1rem"
  },
  {
    "name": "radius-2xl",
    "value": "1.5rem"
  },
  {
    "name": "radius-full",
    "value": "999px"
  }
]

export const sizeElement: Token[] = [
  {
    "name": "size-element-sm",
    "value": "calc(1.5rem * var(--db-sizing-scalar))"
  },
  {
    "name": "size-element-md",
    "value": "calc(2rem * var(--db-sizing-scalar))"
  }
]

export const sizeIcon: Token[] = [
  {
    "name": "size-icon-xs",
    "value": "calc(0.75rem * var(--db-sizing-scalar))"
  },
  {
    "name": "size-icon-sm",
    "value": "calc(0.875rem * var(--db-sizing-scalar))"
  },
  {
    "name": "size-icon-md",
    "value": "calc(1rem * var(--db-sizing-scalar))"
  },
  {
    "name": "size-icon-lg",
    "value": "calc(1.25rem * var(--db-sizing-scalar))"
  },
  {
    "name": "size-icon-xl",
    "value": "calc(1.5rem * var(--db-sizing-scalar))"
  }
]

export const borderWidth: Token[] = [
  {
    "name": "border-width-none",
    "value": "0px"
  },
  {
    "name": "border-width-thin",
    "value": "1px"
  },
  {
    "name": "border-width-thick",
    "value": "2px"
  }
]

export const elevation: Token[] = [
  {
    "name": "elevation-0",
    "value": "none"
  },
  {
    "name": "elevation-1",
    "value": "0 8px 40px rgba(0, 0, 0, 0.13)"
  },
  {
    "name": "elevation-2",
    "value": "0 2px 16px rgba(0, 0, 0, 0.08)"
  },
  {
    "name": "elevation-3",
    "value": "0 2px 3px rgba(0, 0, 0, 0.1), 0 1px 0 rgba(0, 0, 0, 0.05)"
  }
]

export const duration: Token[] = [
  {
    "name": "duration-fast-min",
    "value": "130ms"
  },
  {
    "name": "duration-fast",
    "value": "175ms"
  },
  {
    "name": "duration-fast-max",
    "value": "230ms"
  },
  {
    "name": "duration-medium-min",
    "value": "310ms"
  },
  {
    "name": "duration-medium",
    "value": "410ms"
  },
  {
    "name": "duration-medium-max",
    "value": "550ms"
  }
]

export const easing: Token[] = [
  {
    "name": "ease-standard",
    "value": "cubic-bezier(0.24, 1, 0.4, 1)"
  }
]

export const scalars: Token[] = [
  {
    "name": "spacing-unit",
    "value": "0.25rem"
  },
  {
    "name": "density-scalar",
    "value": "1"
  },
  {
    "name": "spacing-scalar",
    "value": "1"
  },
  {
    "name": "sizing-scalar",
    "value": "1"
  },
  {
    "name": "type-scalar",
    "value": "1"
  }
]

export const tokenCounts = {
  "colorGroups": 87,
  "space": 9,
  "spaceInline": 2,
  "radius": 6,
  "sizeElement": 2,
  "sizeIcon": 5,
  "borderWidth": 3,
  "elevation": 4,
  "duration": 6,
  "easing": 1,
  "scalars": 5
}
