// Generated by scripts/generate-token-consumption.mjs — do not edit by hand.
// Measured against the repo, so a family that nothing reads reports itself.

export type Consumer = { file: string; refs: number }
export type Bridge = { namespace: string; kind: string; file: string; uses: number; files: number }
/** The Tailwind namespace rendering what this family was meant to render. */
export type Superseded = { namespace: string; uses: number; files: number }
export type Family = {
  key: string
  label: string
  /** How many of the thing a reader counts — styles for type, levels for elevation. */
  count: number
  /** The noun for that thing, so a bare number cannot be read as a property count. */
  unit: string
  /** CSS custom properties emitted. Larger than `count` only where one thing sets several. */
  properties: number
  bridge: Bridge | null
  /** Set only when the family is not live and something else does its job. */
  superseded: Superseded | null
  systemRefs: number
  systemConsumers: Consumer[]
  portalRefs: number
  portalConsumers: Consumer[]
  live: boolean
}
/** bridges = Tailwind namespaces whose value resolves through this dial. */
export type Scalar = {
  name: string
  drives: string[]
  bridges: Array<{ namespace: string; uses: number }>
  live: boolean
}
export type TailwindNamespace = {
  namespace: string
  probe: string | null
  tailwindValue: string | null
  overriddenIn: string | null
  overriddenTo: string | null
  /** override = DBUI replaces a Tailwind key · addition = DBUI adds one to the
   *  namespace · tailwind = Tailwind's value stands · utility = no theme key. */
  origin: "override" | "addition" | "tailwind" | "utility"
  uses: number
  files: number
}
export type ThemeOverride = { file: string; key: string; value: string; fromToken: boolean }
export type Hardcoded = {
  uses: number
  files: Array<{ file: string; refs: number; samples: string[] }>
  samples: string[]
}

export const families: Family[] = [
  {
    "key": "color",
    "label": "Color",
    "count": 85,
    "unit": "colors",
    "properties": 85,
    "bridge": {
      "namespace": "--color-*",
      "kind": "theme",
      "file": "packages/dbui/src/tokens/tokens.css",
      "uses": 1023,
      "files": 75
    },
    "superseded": null,
    "systemRefs": 23,
    "systemConsumers": [
      {
        "file": "packages/dbui/src/components/ui/sonner.tsx",
        "refs": 15
      },
      {
        "file": "packages/dbui/src/tokens/globals.css",
        "refs": 2
      },
      {
        "file": "packages/dbui-shells/src/components/AssistantPanel.tsx",
        "refs": 2
      },
      {
        "file": "packages/dbui-genie/src/components/prompt-input.tsx",
        "refs": 2
      },
      {
        "file": "packages/dbui/src/components/ui/alert-dialog.tsx",
        "refs": 1
      },
      {
        "file": "packages/dbui/src/components/ui/dialog.tsx",
        "refs": 1
      }
    ],
    "portalRefs": 4,
    "portalConsumers": [
      {
        "file": "apps/portal/src/app/globals.css",
        "refs": 2
      },
      {
        "file": "apps/portal/src/app/page.tsx",
        "refs": 2
      }
    ],
    "live": true
  },
  {
    "key": "type",
    "label": "Type",
    "count": 14,
    "unit": "styles",
    "properties": 74,
    "bridge": {
      "namespace": "type-*",
      "kind": "utility",
      "file": "packages/dbui/src/tokens/type.css",
      "uses": 161,
      "files": 56
    },
    "superseded": null,
    "systemRefs": 3,
    "systemConsumers": [
      {
        "file": "packages/dbui/src/tokens/globals.css",
        "refs": 3
      }
    ],
    "portalRefs": 5,
    "portalConsumers": [
      {
        "file": "apps/portal/src/app/globals.css",
        "refs": 5
      }
    ],
    "live": true
  },
  {
    "key": "elevation",
    "label": "Elevation",
    "count": 4,
    "unit": "levels",
    "properties": 4,
    "bridge": null,
    "superseded": {
      "namespace": "--shadow-*",
      "uses": 83,
      "files": 33
    },
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 1,
    "portalConsumers": [
      {
        "file": "apps/portal/src/components/ShellPreview.tsx",
        "refs": 1
      }
    ],
    "live": false
  },
  {
    "key": "scalars",
    "label": "Scalars",
    "count": 4,
    "unit": "dials",
    "properties": 4,
    "bridge": null,
    "superseded": null,
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 2,
    "portalConsumers": [
      {
        "file": "apps/portal/src/components/layout-data.ts",
        "refs": 2
      }
    ],
    "live": true
  },
  {
    "key": "space",
    "label": "Space",
    "count": 10,
    "unit": "steps",
    "properties": 10,
    "bridge": null,
    "superseded": {
      "namespace": "--spacing",
      "uses": 818,
      "files": 78
    },
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 0,
    "portalConsumers": [],
    "live": false
  },
  {
    "key": "size",
    "label": "Size",
    "count": 7,
    "unit": "steps",
    "properties": 7,
    "bridge": null,
    "superseded": {
      "namespace": "--spacing",
      "uses": 818,
      "files": 78
    },
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 0,
    "portalConsumers": [],
    "live": false
  },
  {
    "key": "radius",
    "label": "Radius",
    "count": 6,
    "unit": "steps",
    "properties": 6,
    "bridge": {
      "namespace": "--radius-*",
      "kind": "theme",
      "file": "packages/dbui/src/tokens/tokens.css",
      "uses": 134,
      "files": 58
    },
    "superseded": null,
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 0,
    "portalConsumers": [],
    "live": true
  },
  {
    "key": "border",
    "label": "Border width",
    "count": 3,
    "unit": "widths",
    "properties": 3,
    "bridge": null,
    "superseded": {
      "namespace": "border and divide width",
      "uses": 82,
      "files": 44
    },
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 0,
    "portalConsumers": [],
    "live": false
  },
  {
    "key": "motion",
    "label": "Motion",
    "count": 7,
    "unit": "values",
    "properties": 7,
    "bridge": null,
    "superseded": {
      "namespace": "--default-transition-duration",
      "uses": 29,
      "files": 22
    },
    "systemRefs": 0,
    "systemConsumers": [],
    "portalRefs": 0,
    "portalConsumers": [],
    "live": false
  }
]

export const scalars: Scalar[] = [
  {
    "name": "--db-spacing-unit",
    "drives": [
      "space"
    ],
    "bridges": [
      {
        "namespace": "--spacing",
        "uses": 818
      }
    ],
    "live": true
  },
  {
    "name": "--db-density-scalar",
    "drives": [
      "space"
    ],
    "bridges": [
      {
        "namespace": "--spacing",
        "uses": 818
      }
    ],
    "live": true
  },
  {
    "name": "--db-sizing-scalar",
    "drives": [
      "size"
    ],
    "bridges": [],
    "live": false
  },
  {
    "name": "--db-type-scalar",
    "drives": [
      "type"
    ],
    "bridges": [],
    "live": true
  }
]

export const tailwind: TailwindNamespace[] = [
  {
    "namespace": "--spacing",
    "probe": "--spacing",
    "tailwindValue": "0.25rem",
    "overriddenIn": "packages/dbui/src/tokens/tokens.css",
    "overriddenTo": "calc(var(--db-spacing-unit) * var(--db-density-scalar))",
    "origin": "override",
    "uses": 818,
    "files": 78
  },
  {
    "namespace": "--radius-*",
    "probe": "--radius-md",
    "tailwindValue": "0.375rem",
    "overriddenIn": "packages/dbui/src/tokens/tokens.css",
    "overriddenTo": "var(--db-radius-md)",
    "origin": "override",
    "uses": 126,
    "files": 56
  },
  {
    "namespace": "--shadow-*",
    "probe": "--shadow-lg",
    "tailwindValue": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 83,
    "files": 33
  },
  {
    "namespace": "border and divide width",
    "probe": null,
    "tailwindValue": null,
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "utility",
    "uses": 82,
    "files": 44
  },
  {
    "namespace": "ring and outline width",
    "probe": null,
    "tailwindValue": null,
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "utility",
    "uses": 57,
    "files": 31
  },
  {
    "namespace": "--animate-*",
    "probe": "--animate-spin",
    "tailwindValue": "spin 1s linear infinite",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 40,
    "files": 18
  },
  {
    "namespace": "z-index scale",
    "probe": null,
    "tailwindValue": null,
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "utility",
    "uses": 34,
    "files": 20
  },
  {
    "namespace": "--default-transition-duration",
    "probe": "--default-transition-duration",
    "tailwindValue": "150ms",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 29,
    "files": 22
  },
  {
    "namespace": "duration-* and ease-*",
    "probe": null,
    "tailwindValue": null,
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "utility",
    "uses": 14,
    "files": 10
  },
  {
    "namespace": "--font-weight-*",
    "probe": "--font-weight-semibold",
    "tailwindValue": "600",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 14,
    "files": 11
  },
  {
    "namespace": "--breakpoint-*",
    "probe": "--breakpoint-sm",
    "tailwindValue": "40rem",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 13,
    "files": 4
  },
  {
    "namespace": "--shadow-focus",
    "probe": "--shadow-focus",
    "tailwindValue": null,
    "overriddenIn": "packages/dbui/src/tokens/globals.css",
    "overriddenTo": "0 0 0 1px var(--db-focus-ring-offset), 0 0 0 3px var(--db-focus-ring)",
    "origin": "addition",
    "uses": 5,
    "files": 4
  },
  {
    "namespace": "--container-*",
    "probe": "--container-sm",
    "tailwindValue": "24rem",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 3,
    "files": 2
  },
  {
    "namespace": "--leading-*",
    "probe": "--leading-snug",
    "tailwindValue": "1.375",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 3,
    "files": 2
  },
  {
    "namespace": "--blur-*",
    "probe": "--blur-xs",
    "tailwindValue": "4px",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 2,
    "files": 2
  },
  {
    "namespace": "--text-*",
    "probe": "--text-sm",
    "tailwindValue": "0.875rem",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 0,
    "files": 0
  },
  {
    "namespace": "--tracking-*",
    "probe": "--tracking-tight",
    "tailwindValue": "-0.025em",
    "overriddenIn": null,
    "overriddenTo": null,
    "origin": "tailwind",
    "uses": 0,
    "files": 0
  }
]

export const themeOverrides: ThemeOverride[] = [
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--color-icon-folder",
    "value": "var(--icon-folder)",
    "fromToken": false
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--color-ai-gradient-start",
    "value": "var(--ai-gradient-start)",
    "fromToken": false
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--color-ai-gradient-mid",
    "value": "var(--ai-gradient-mid)",
    "fromToken": false
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--color-ai-gradient-end",
    "value": "var(--ai-gradient-end)",
    "fromToken": false
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--shadow-focus",
    "value": "0 0 0 1px var(--db-focus-ring-offset), 0 0 0 3px var(--db-focus-ring)",
    "fromToken": true
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--font-sans",
    "value": "var(--db-font-family)",
    "fromToken": true
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--font-display",
    "value": "var(--db-font-family)",
    "fromToken": true
  },
  {
    "file": "packages/dbui/src/tokens/globals.css",
    "key": "--font-mono",
    "value": "var(--db-mono-font-family)",
    "fromToken": true
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--color-icon-folder",
    "value": "var(--icon-folder)",
    "fromToken": false
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--color-ai-gradient-start",
    "value": "var(--ai-gradient-start)",
    "fromToken": false
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--color-ai-gradient-mid",
    "value": "var(--ai-gradient-mid)",
    "fromToken": false
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--color-ai-gradient-end",
    "value": "var(--ai-gradient-end)",
    "fromToken": false
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--shadow-focus",
    "value": "0 0 0 1px var(--db-focus-ring-offset), 0 0 0 3px var(--db-focus-ring)",
    "fromToken": true
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--font-sans",
    "value": "var(--db-font-family)",
    "fromToken": true
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--font-display",
    "value": "var(--db-font-family)",
    "fromToken": true
  },
  {
    "file": "apps/portal/src/app/globals.css",
    "key": "--font-mono",
    "value": "var(--db-mono-font-family)",
    "fromToken": true
  }
]

export const hardcoded: Hardcoded = {
  "uses": 48,
  "files": [
    {
      "file": "packages/dbui-shells/src/shells/CatalogExplorer.tsx",
      "refs": 5,
      "samples": [
        "w-[280px]",
        "w-[240px]",
        "w-[220px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/input-group.tsx",
      "refs": 4,
      "samples": [
        "has-[>button]:ml-[-0.3rem]",
        "has-[>kbd]:ml-[-0.15rem]",
        "has-[>button]:mr-[-0.3rem]",
        "has-[>kbd]:mr-[-0.15rem]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/compositions/DataTreeExplorer.tsx",
      "refs": 4,
      "samples": [
        "w-[280px]",
        "w-[240px]",
        "w-[220px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/chart.tsx",
      "refs": 3,
      "samples": [
        "rounded-[2px]",
        "border-[1.5px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/dialog.tsx",
      "refs": 3,
      "samples": [
        "data-[size=normal]:sm:max-w-[640px]",
        "data-[size=wide]:sm:max-w-[880px]",
        "data-[size=extrawide]:sm:max-w-[1200px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/drawer.tsx",
      "refs": 3,
      "samples": [
        "data-[vaul-drawer-direction=left]:sm:max-w-[360px]",
        "data-[vaul-drawer-direction=right]:sm:max-w-[360px]",
        "w-[100px]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/components/FacetedFilter.tsx",
      "refs": 3,
      "samples": [
        "w-[240px]",
        "max-w-[240px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/key-value-pair.tsx",
      "refs": 2,
      "samples": [
        "w-[280px]",
        "w-[120px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/menubar.tsx",
      "refs": 2,
      "samples": [
        "p-[3px]",
        "py-[2px]"
      ]
    },
    {
      "file": "packages/dbui/src/rules/layout-rules.ts",
      "refs": 2,
      "samples": [
        "w-[180px]",
        "rounded-[8px]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/components/AssistantPanel.tsx",
      "refs": 2,
      "samples": [
        "w-[360px]",
        "min-h-[36px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/checkbox.tsx",
      "refs": 1,
      "samples": [
        "rounded-[4px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/combobox.tsx",
      "refs": 1,
      "samples": [
        "max-w-[160px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/dropdown-menu.tsx",
      "refs": 1,
      "samples": [
        "min-w-[96px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/hover-card.tsx",
      "refs": 1,
      "samples": [
        "w-[280px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/item.tsx",
      "refs": 1,
      "samples": [
        "ring-[3px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/platform-header.tsx",
      "refs": 1,
      "samples": [
        "w-[552px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/popover.tsx",
      "refs": 1,
      "samples": [
        "w-[280px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/scroll-area.tsx",
      "refs": 1,
      "samples": [
        "ring-[3px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/table.tsx",
      "refs": 1,
      "samples": [
        "rounded-[1px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/tabs.tsx",
      "refs": 1,
      "samples": [
        "p-[3px]"
      ]
    },
    {
      "file": "packages/dbui/src/components/ui/tooltip.tsx",
      "refs": 1,
      "samples": [
        "rounded-[2px]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/components/PlatformHeader.tsx",
      "refs": 1,
      "samples": [
        "min-w-[56px]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/components/PlatformNav.tsx",
      "refs": 1,
      "samples": [
        "w-[180px]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/components/SearchPopup.tsx",
      "refs": 1,
      "samples": [
        "max-h-[320px]"
      ]
    },
    {
      "file": "packages/dbui-shells/src/compositions/PreviewPopup.tsx",
      "refs": 1,
      "samples": [
        "w-[80px]"
      ]
    }
  ],
  "samples": [
    "w-[280px]",
    "w-[240px]",
    "w-[220px]",
    "has-[>button]:ml-[-0.3rem]",
    "has-[>kbd]:ml-[-0.15rem]",
    "has-[>button]:mr-[-0.3rem]",
    "has-[>kbd]:mr-[-0.15rem]",
    "rounded-[2px]",
    "border-[1.5px]",
    "data-[size=normal]:sm:max-w-[640px]",
    "data-[size=wide]:sm:max-w-[880px]",
    "data-[size=extrawide]:sm:max-w-[1200px]"
  ]
}

export const tailwindVersion = "4.2.2"
